In [55]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [56]:
data = pd.read_csv(r'C:\Users\User\Downloads\hospital_deaths_train.csv')
data = data.fillna(np.mean(data, axis = 0))
data = data.drop('recordid', axis = 1)
X = data.drop('In-hospital_death', axis = 1)
y = data['In-hospital_death']
x_train, x_test, y_train, y_test = train_test_split(X, y,random_state=0, test_size=0.2)
data

,In-hospital_death,Age,Gender,Height,Weight,CCU,CSRU,SICU,DiasABP_first,GCS_first,...,SysABP_last,TroponinI_last,TroponinT_last,WBC_last,Weight_last,pH_last,MechVentStartTime,MechVentDuration,MechVentLast8Hour,UrineOutputSum
0,0,69.0,1.0,172.700000,63.700000,0,0,0,59.000000,3.000000,...,119.000000,4.600000,1.020169,17.2,63.70000,7.410000,105.000000,2580.000000,1.000000,12.000000
1,0,72.0,1.0,172.633034,81.618834,0,0,0,62.277926,10.028429,...,122.208684,6.376074,0.230000,21.9,85.21851,7.399146,292.907282,1907.607282,0.623301,12.357282
2,0,29.0,0.0,172.633034,90.000000,0,0,0,37.000000,10.000000,...,124.000000,6.376074,1.020169,11.1,106.30000,7.400000,103.000000,2700.000000,1.000000,14.000000
3,0,73.0,1.0,175.300000,89.100000,0,1,0,58.000000,3.000000,...,148.000000,6.376074,1.020169,18.3,94.20000,7.450000,144.000000,2115.000000,0.000000,12.000000
4,0,74.0,0.0,172.633034,78.000000,0,0,1,47.000000,3.000000,...,187.000000,6.376074,1.020169,17.7,85.21851,7.260000,75.000000,2280.000000,0.000000,18.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3245,0,62.0,0.0,170.200000,54.200000,0,0,0,72.000000,15.000000,...,115.000000,6.376074,1.020169,21.7,66.80000,7.410000,1703.000000,1080.000000,1.000000,8.000000
3246,0,34.0,1.0,172.633034,81.800000,1,0,0,84.000000,15.000000,...,193.000000,6.376074,1.020169,10.2,85.21851,7.410000,292.907282,1907.607282,0.623301,12.357282
3247,0,60.0,0.0,172.633034,60.000000,0,0,0,72.000000,3.000000,...,106.000000,6.376074,3.990000,15.1,60.00000,7.380000,126.000000,2580.000000,1.000000,17.000000
3248,0,68.0,0.0,172.633034,78.800000,0,0,0,62.277926,15.000000,...,122.208684,6.376074,1.020169,11.3,78.80000,7.399146,292.907282,1907.607282,0.623301,12.357282
3249,0,62.0,1.0,182.900000,80.500000,0,1,0,46.000000,3.000000,...,115.000000,6.376074,1.020169,9.4,89.80000,7.460000,149.000000,720.000000,0.000000,5.000000

In [57]:
model = tf.keras.models.Sequential([
  #tf.keras.layers.Flatten(input_shape=(2600,114)),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dense(128, activation = 'relu'),
  tf.keras.layers.Dense(32, activation = 'sigmoid')
  tf.keras.layers.Dense(128, activation = 'tanh'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(2)
])

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1678279593.py, line 5)

In [58]:
model.compile(optimizer = tf.keras.optimizers.Adam(),
              loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics = ['accuracy'])

In [59]:
model.fit(x_train, y_train, epochs=20)

Epoch 1/20
82/82 [==============================] - 1s 1ms/step - loss: 0.3768 - accuracy: 0.8646
Epoch 2/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3725 - accuracy: 0.8646
Epoch 3/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3773 - accuracy: 0.8635
Epoch 4/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3744 - accuracy: 0.8646
Epoch 5/20
82/82 [==============================] - 0s 2ms/step - loss: 0.3698 - accuracy: 0.8646
Epoch 6/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3685 - accuracy: 0.8650
Epoch 7/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3707 - accuracy: 0.8654
Epoch 8/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3777 - accuracy: 0.8642
Epoch 9/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3780 - accuracy: 0.8658
Epoch 10/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3821 - accuracy: 0.8642
Epoch 11/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3854 - accuracy: 0.8658
Epoch 12/20
82/82 [==============================] - 0s 2ms/step - loss: 0.3807 - accuracy: 0.8646
Epoch 13/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3782 - accuracy: 0.8658
Epoch 14/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3824 - accuracy: 0.8654
Epoch 15/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3745 - accuracy: 0.8665
Epoch 16/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3806 - accuracy: 0.8658
Epoch 17/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3752 - accuracy: 0.8677
Epoch 18/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3733 - accuracy: 0.8669
Epoch 19/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3821 - accuracy: 0.8662
Epoch 20/20
82/82 [==============================] - 0s 1ms/step - loss: 0.3781 - accuracy: 0.8658

In [60]:
d = pd.read_csv(r'C:\Users\User\Downloads\hospital_deaths_test.csv')
d = d.fillna(np.mean(data, axis = 0))
d = d.drop('recordid', axis = 1)
X = d.drop('In-hospital_death', axis = 1)
y = d['In-hospital_death']

In [61]:
model.evaluate(X,  y, verbose=2)

24/24 - 0s - loss: 0.3961 - accuracy: 0.8587 - 95ms/epoch - 4ms/step

[0.3961319625377655, 0.8586666584014893]